openapi: 3.0.0
info:
  title: Mitarbeiter
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /employees:
    get:
      summary: Find all employees
      tags:
        - Employees
      responses: {}
      operationId: get-employees
components:
  schemas:
    Employee:
      title: Employee
      type: object
      properties:
        id:
          type: string
      x-tags:
        - Models
