openapi: 3.0.0
info:
  title: Kooperationen
  version: '1.0'
  description: |-
    Eine Kooperation bezeichnet die Zusammenarbeit zwischen Mitarbeitern und Firmen oder Mitarbeitern und Firmen untereinander. Sie entstehen aus Kooperationsverträgen, die in der Plattform über die Weboberfläche angelegt und gepflegt werden können.
    Über diese Schnittstelle können u.a. die aktuellen Kooperationen eines Mitarbeiters oder einer Firma abgefragt werden.
  contact:
    name: ContactName
    email: ContactEmail@drklein.de
  termsOfService: Terms of Service
servers:
  - url: 'https://api.drklein-plattform.de'
    description: PROD
paths:
  /cooperations:
    get:
      summary: Find all
      tags:
        - Cooperations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/cooperations.v1.yaml
      operationId: get-cooperations
      description: Zeige alle Kooperationen der Firma oder filtere sie nach einem Mitarbeiter oder einer Firma auf einer beliebigen Vertragsseite.
      parameters:
        - schema:
            type: string
          in: query
          name: contractingPartnerId
        - schema:
            type: string
          in: query
          name: contractingPartner.externalKey
components:
  schemas: {}
  securitySchemes:
    Dr.Klein Plattform ID Service:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: Alle Aufrufe der Public Api benötigen einen gültigen OAuth Token vom ID Service der Dr.Klein Plattform.
