openapi: 3.0.0
info:
  title: Dr. Klein Plattform API
  version: '1.0'
  description: |-
    # Nutzung der API
    Jede Firma innerhalb der Dr. Klein Plattform hat einen eindeutigen "companySlug", der immer im Pfad mit angegeben werden muss. Der Slug von Dr. Klein ist beispielsweise 'drklein', daher sieht der Pfad für Kooperationspartner von Dr. Klein so aus:

    https://api.drklein-plattform.de/drklein/v1/cooperations

    # Kooperation

    Eine Kooperation bezeichnet die Zusammenarbeit zwischen zwei Partnern. Ein Partner ist ein Mitarbeiter an einem Standort. Sie entstehen aus Kooperationsverträgen, die in der Plattform über die Weboberfläche angelegt und gepflegt werden können.
    Über diese Schnittstelle können u.a. die aktuellen Kooperationen eines Partners abgefragt werden.
  contact:
    name: Timo Lange
    email: das-produkt@drklein.de
  termsOfService: Terms of Service
servers:
  - url: 'https://api.drklein-plattform.de/{companySlug}'
    description: PROD
paths:
  /cooperations:
    get:
      summary: Find all
      tags:
        - Cooperations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ../models/cooperations.v1.yaml
      operationId: get-cooperations
      description: Zeige alle Kooperationen der Firma oder filtere sie nach einem Partner.
      parameters:
        - schema:
            type: string
          in: query
          name: contractingPartnerId
        - schema:
            type: string
          in: query
          name: contractingPartner.externalKey
components:
  schemas: {}
  securitySchemes:
    Dr.Klein Plattform ID Service:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: ''
          refreshUrl: ''
          scopes: {}
      description: Alle Aufrufe der Public Api benötigen einen gültigen OAuth Token vom ID Service der Dr.Klein Plattform.
