openapi: 3.0.0
info:
  title: Kooperationen
  version: '1.0'
  description: Kooperationen
  contact:
    name: ContactName
    email: ContactEmail@drklein.de
  termsOfService: Terms of Service
servers:
  - url: 'https://api.drklein-plattform.de'
    description: PROD
paths:
  /cooperations:
    get:
      summary: Find all cooperations
      tags:
        - Cooperations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ../models/cooperation.v1.yaml
      operationId: get-cooperations
components:
  schemas: {}
  securitySchemes:
    Dr.Klein Plattform ID Service:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://id.drklein-plattform.de/auth/token'
          refreshUrl: ''
          scopes:
            openid: ''
      description: ''
