swagger: '2.0'
info:
  title: Mitarbeiter
  version: '1.0'
host: 'localhost:3000'
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /employees:
    get:
      summary: Find all
      tags:
        - Employees
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Employee'
      operationId: get-employees
      description: Find all description
definitions:
  Employee:
    title: Employee
    type: object
    properties:
      id:
        type: string
