openapi: 3.0.0
info:
  title: Public Api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /cooperation-contracts:
    get:
      summary: Find all cooperation contracts
      tags: []
      responses: {}
      operationId: get-cooperation-contracts
      description: Find all cooperation contracts for your company. When you specify a contractingPartner you will get all cooperation-contracts where the contractingPartner is on one side of the contract.
components:
  schemas:
    CooperationContract:
      title: CooperationContract
      type: object
      properties:
        id:
          type: string
