openapi: 3.0.0
info:
  title: tests
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /tests:
    get:
      summary: Find all tests
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
      operationId: get-tests
      description: ''
      requestBody: {}
components:
  schemas:
    Test:
      title: Test
      type: object
      properties:
        id:
          type: string
